# Generated by Django 5.0.1 on 2025-02-21 20:06

import lampi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lampi',
            fields=[
                ('name', models.CharField(default='My LAMPI', max_length=50)),
                ('device_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(lampi.models.get_parked_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
