# Generated by Django 5.0.1 on 2025-03-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='d9581639822d422894d289d876638ffe', max_length=32),
        ),
    ]
