# Generated by Django 5.0.1 on 2025-03-02 15:56

import lampi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='f400b4c9e20f439c8f5b92dde3a07feb',
                                    max_length=32),
        ),
        migrations.AlterField(
            model_name='lampi',
            name='user',
            field=models.ForeignKey(
                on_delete=models.SET(lampi.models.get_parked_user),
                to=settings.AUTH_USER_MODEL),
        ),
    ]
