# Generated by Django 5.0.1 on 2025-03-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0002_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='988822bb27f94313a59dcf80528b035c', max_length=32),
        ),
    ]
