# Generated by Django 5.0.1 on 2025-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0002_lampi_association_code_alter_lampi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='f7a4c0da93904af296c390d37d12745a', max_length=32),
        ),
    ]
