# Generated by Django 5.0.1 on 2025-03-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0003_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='67211dbdc86445e892bb0ef15908eb49', max_length=32),
        ),
    ]
