# Generated by Django 5.0.1 on 2025-03-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0003_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='b3f728f285df48ceaf917f14161cbb64', max_length=32),
        ),
    ]
