# Generated by Django 5.0.1 on 2025-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0004_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(
                default='9880343837264dfdb1181e0ca224f771', max_length=32),
        ),
    ]
