# Generated by Django 5.0.1 on 2025-03-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0004_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='d3d178a068cf484eab45f2a928c5abe7', max_length=32),
        ),
    ]
