# Generated by Django 5.0.1 on 2025-03-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0005_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='b64366722e614f5bb7a8a84bc748fea9', max_length=32),
        ),
    ]
