# Generated by Django 5.0.1 on 2025-04-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0005_senderdevice_devicedata_cpuload_diskstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='lampi.senderdevice'),
        ),
    ]
