# Generated by Django 5.0.1 on 2025-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0005_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(
                default='d9074a8c1db14a0cb7c8fed76f45db5a', max_length=32),
        ),
    ]
