# Generated by Django 5.0.1 on 2025-03-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0006_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(
                default='920cf24388ee4972aa44e843f81cfcd5', max_length=32),
        ),
    ]
