# Generated by Django 5.0.1 on 2025-03-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0007_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='1b1c3f44eb7d44ecaa7d329e6ee6f062', max_length=32),
        ),
    ]
