# Generated by Django 5.0.1 on 2025-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0007_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='1267ac2b10a1429dbbf76ffd39fb0a80', max_length=32),
        ),
    ]
