# Generated by Django 5.0.1 on 2025-03-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0008_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(
                default='895212076e364be782618a212026ce52', max_length=32),
        ),
    ]
