# Generated by Django 5.0.1 on 2025-03-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0009_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(
                default='448a59c744ce4031b62bf2ae54dd5ccb', max_length=32),
        ),
    ]
