# Generated by Django 5.0.1 on 2025-03-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0010_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(
                default='151c24b01b304600b3018244eae5e977', max_length=32),
        ),
    ]
