# Generated by Django 5.0.1 on 2025-03-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0011_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='f7db799d42884e53a4e745ec08d9da66', max_length=32),
        ),
    ]
