# Generated by Django 5.0.1 on 2025-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0012_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='e072e84bfdd84867936dca8827685e2f', max_length=32),
        ),
    ]
