# Generated by Django 5.0.1 on 2025-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0013_alter_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='association_code',
            field=models.CharField(default='514c0a90a6ed4ee9b9b779f10a861911',
                                   max_length=32),
        ),
    ]
