#!/bin/bash

# copy system files
cp /opt/lampi/system/lampi_app.service /etc/systemd/system/lampi_app.service
cp /opt/lampi/system/lampi_bluetooth.service /etc/systemd/system/lampi_bluetooth.service
cp /opt/lampi/system/lampi_hci0.service /etc/systemd/system/lampi_hci0.service
cp /opt/lampi/system/lampi_service.service /etc/systemd/system/lampi_service.service


systemctl daemon-reload

systemctl start lampi_service
systemctl start lampi_bluetooth
systemctl start lampi_app

systemctl enable lampi_service
systemctl enable lampi_bluetooth
systemctl enable lampi_app
