---
# vars file for cloud

cache_update_valid_secs: 900

# chapter 4 variables
apt_pkg_mosquitto: mosquitto=2.0.*
apt_pkg_mosquitto_clients: mosquitto-clients=2.0.*

# chapter 5 variables
connected_devices_git_repo_url: "git@github.com:CWRU-Connected-Devices/connected-devices-spring25.git"
connected_devices_git_repo_version: main
repo_directory: /home/ubuntu/connected-devices
root_web_directory: /home/ubuntu/connected-devices/Web/static
venv_directory: "/home/ubuntu/ec2-venv"
apt_pkg_python3_distutils: python3-distutils=3.10.*
apt_pkg_python3_10_venv: python3.10-venv=3.10.*
apt_pkg_nginx: nginx=1.18.*
apt_pkg_git: git=1:2.34.*
apt_pkg_build_essential: build-essential=12.9*
apt_pkg_python3_dev: python3-dev=3.10.*
requirements_file_path: "{{ repo_directory }}/ansible/roles/cloud/files/pip_requirements/requirements.txt"

# chapter 6 variables
django_dir: "{{repo_directory}}/Web/lampisite"
django_admin_username: admin
django_admin_email: blah@blah.com
django_admin_password: iot12345
django_settings: lampisite.settings
lampi_mqtt_daemon_service_file: lampi_mqtt_daemon.service

# chapter 7 variables
lampi_uwsgi_service_file: lampi_uwsgi.service

# chapter 11 variables
gpg_key_type: RSA
gpg_key_length: 4096
gpg_real_name: iot student
gpg_key_config_path: /tmp/ansible.gpg_key_gen.conf
apt_repo_full_name: EECS397 Connected Devices
apt_repo_name: EECS397 Connected Devices Repository
apt_repo_short_name: eecs397
apt_repo_subkey_id: FILL_IN
apt_pkg_rng_tools: rng-tools=2.3
apt_pkg_reprepro: reprepro=5.3.*

# chapter 12 variables
lampi_db_name: lampi
lampi_db_user: lampiuser
lampi_db_password: eecs397-iot
apt_pkg_memcached: memcached=1.6.*
apt_pkg_libpq_dev: libpq-dev=14.*
apt_pkg_postgresql: postgresql=14+*
apt_pkg_postgresql_contrib: postgresql-contrib=14+*
apt_pkg_acl: acl=2.3.*
